"""
FolderTreeConstants - Constantes compartidas para el sidebar.

Centraliza todas las constantes de layout y posicionamiento.
"""

from PySide6.QtGui import QColor


# Área de controles (chevron, menú, separador)
CONTROLS_AREA_PAD_X_RIGHT = 10
CONTROLS_AREA_PADDING = 4
CONTROLS_AREA_OFFSET = 8
CONTROLS_AREA_BUTTON_SIZE = 24
CONTROLS_AREA_SEPARATOR_MARGIN = 12

CONTROLS_AREA_TOTAL_OFFSET = (
    CONTROLS_AREA_PAD_X_RIGHT + 
    CONTROLS_AREA_PADDING + 
    CONTROLS_AREA_OFFSET + 
    CONTROLS_AREA_BUTTON_SIZE + 
    CONTROLS_AREA_SEPARATOR_MARGIN
)

# Botón de menú (tres puntitos)
MENU_BUTTON_SIZE = 24
MENU_BUTTON_PADDING = 4
MENU_BUTTON_VERTICAL_OFFSET = 6
MENU_BUTTON_MIN_TOP_MARGIN = 2

# Chevron (flecha de expansión)
ARROW_SIZE = 6
ARROW_BODY_RATIO = 0.6
CHEVRON_CLICKABLE_WIDTH = 32
CHEVRON_CLICKABLE_HEIGHT = 28
CHEVRON_VERTICAL_SPACING = 14
CHEVRON_VERTICAL_OFFSET = 0

# Separadores
SEPARATOR_VERTICAL_COLOR = QColor(255, 255, 255, 40)
SEPARATOR_VERTICAL_MARGIN_TOP = 4
SEPARATOR_VERTICAL_MARGIN_BOTTOM = 4
SEPARATOR_VERTICAL_TEXT_MARGIN = 4

SEPARATOR_HORIZONTAL_COLOR = QColor(255, 255, 255, 23)

# Espaciado de items raíz
ROOT_ITEM_TOP_SPACING = 8

# Padding del contenedor
CONTAINER_PADDING_LEFT = 10

